"""empty message

Revision ID: 154b0a090e62
Revises: e7b419db484a
Create Date: 2017-12-28 14:40:52.361139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154b0a090e62'
down_revision = 'e7b419db484a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('tag', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'tag')
    # ### end Alembic commands ###
